# Generated by Django 3.0.4 on 2020-05-15 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200515_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='tags for post', max_length=33), size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='example.com'),
        ),
    ]
